import { StyleSheet } from 'react-native';

import { screenHeight } from 'styles/theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: '50%',
  },
  stickerContainer: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 25,
    marginBottom: 25,
  },
  sticker: {
    width: '80%',
    height: screenHeight * 0.5,
    borderRadius: 20,
    borderColor: 'grey',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 30,
  },
  cardContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    width: '100%',
    height: '100%',
    borderRadius: 20,
  },
  stickerTitle: {
    fontSize: 24,
    fontFamily: 'Raleway',
    fontWeight: '600',
    textAlign: 'center',
    paddingTop: 5,
  },
  stickerCount: {
    fontSize: 12,
    textAlign: 'center',
    marginLeft: 34,
    width: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#04B600',
  },
  bigHeader: {
    fontSize: 40,
    fontWeight: '800',
    color: '#F2F2F2',
    textAlign: 'left',
    margin: 20,
    marginTop: 40,
    width: '100%',
    height: 100,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    fontFamily: 'Raleway',
  },
  linearGradient: {
    flex: 1,
    width: '100%',
    height: 120,
    borderRadius: 20,
  },
  buttonsContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '90%',
    marginBottom: 40,
  },
  buttonRed: {
    width: '45%',
    height: 50,
    borderRadius: 20,
    backgroundColor: '#F2F2F2',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  buttonGreen: {
    width: '45%',
    height: 50,
    borderRadius: 20,
    backgroundColor: '#F2F2F2',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  linearGradientButton: {
    width: '100%',
    height: '100%',
    borderRadius: 20,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'grey',
    fontFamily: 'Raleway',
  },
  stickerText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'grey',
    fontFamily: 'Raleway',
  },
  stickerCountry: {
    fontSize: 36,
    color: 'grey',
    fontFamily: 'Raleway',
    textAlign: 'center',
    marginTop: 15,
  },
  stickerId: {
    fontSize: 36,
    fontWeight: 'bold',
    color: 'grey',
    fontFamily: 'Raleway',
    textAlign: 'center',
    marginTop: 20,
    marginBottom: 10,
  },
  adContainer: {
    width: '100%',
    height: 100,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default styles;
