require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'


target 'StickerWap' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'


  # pod 'react-native-config', :path => '../node_modules/react-native-config'

  target 'StickerWapTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
      installer.pods_project.targets.each do |target|
      if target.name == "react-native-config"
        target.remove_from_project
      end
    end
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
